# Copyright 2017 Heptio Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
data:
  # TODO Here is where you add configuration 
  # for router appenders 
  config.json: |- 
    {
      "Appenders": [
        { "Logging": "sink" },
        { "Kafka": "endpoint-details"},
        { "ElasticSearch": "endpoint-details"}
      ]
    }
kind: ConfigMap
metadata:
  name: eventrouter-cm
  namespace: kube-system

---

## Here is the default deployment 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eventrouter
spec:
  # TODO - Set to 2 when ConfigMap locking is merged ~1.7
  # https://github.com/kubernetes/kubernetes/pull/42666
  replicas: 1
  template:
    metadata:
      labels:
        component: eventrouter
        tier: control-plane-addons
    spec:
      containers:
        - name: kube-eventrouter
          # TODO I need a canonical location that we will serve from
          image: eventrouter
          env:
          - name : LOGLVL
            value: 3
          volumeMounts:
          - name: config-volume
            mountPath: /etc/eventrouter
      # TODO - livenessProbe: 
      volumes: 
        - name: config-volume
        configMap:
          name: eventrouter-cm
  
 
