# Copyright 2017 Heptio Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: THIS IS STILL A TODO, cleaning it up

## The following is the configuration input arguments that are used 
apiVersion: v1
kind: ConfigMap
metadata:
  name: eventrouter-config
  namespace: default
data:
  # TODO 
  example.property.1: hello
  example.property.2: world
  example.property.file: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3

---

## 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eventrouter
spec:
  # TODO - Set to 2 when ConfigMap locking is merged ~1.7
  # https://github.com/kubernetes/kubernetes/pull/42666
  replicas: 1
  template:
    metadata:
      labels:
        app: eventrouter
    spec:
      containers:
      - name: eventrouter
        # TODO I need a canonical location that we will serve from
        image: eventrouter:0.1.0
        
--- 
